# Generated by cognito-convert

resource "awscc_cognito_managed_login_branding" "brand" {
  user_pool_id = aws_cognito_user_pool.user_pool.id
  client_id = split("|", awscc_cognito_user_pool_client.pool_client.id)[1]

  settings = jsonencode({
    components = {
      primaryButton = {
        lightMode = {
          hover = {
            backgroundColor = "ffffffff"
            textColor = "0a0a0aff"
          }
          defaults = {
            backgroundColor = "171717ff"
            textColor = "fafafaff"
          }
          active = {
            backgroundColor = "171717ff"
            textColor = "fafafaff"
          }
          disabled = {
            backgroundColor = "f5f5f5ff"
            borderColor = "e5e5e5ff"
          }
        }
        darkMode = {
          hover = {
            backgroundColor = "0a0a0aff"
            textColor = "fafafaff"
          }
          defaults = {
            backgroundColor = "fafafaff"
            textColor = "171717ff"
          }
          active = {
            backgroundColor = "fafafaff"
            textColor = "171717ff"
          }
          disabled = {
            backgroundColor = "262626ff"
            borderColor = "262626ff"
          }
        }
      }
      secondaryButton = {
        lightMode = {
          hover = {
            backgroundColor = "ffffffff"
            borderColor = "e5e5e5ff"
            textColor = "0a0a0aff"
          }
          defaults = {
            backgroundColor = "f5f5f5ff"
            borderColor = "e5e5e5ff"
            textColor = "171717ff"
          }
          active = {
            backgroundColor = "f5f5f5ff"
            borderColor = "e5e5e5ff"
            textColor = "171717ff"
          }
        }
        darkMode = {
          hover = {
            backgroundColor = "0a0a0aff"
            borderColor = "262626ff"
            textColor = "fafafaff"
          }
          defaults = {
            backgroundColor = "262626ff"
            borderColor = "262626ff"
            textColor = "fafafaff"
          }
          active = {
            backgroundColor = "262626ff"
            borderColor = "262626ff"
            textColor = "fafafaff"
          }
        }
      }
      form = {
        lightMode = {
          backgroundColor = "ffffffff"
          borderColor = "e5e5e5ff"
        }
        borderRadius = 10
        darkMode = {
          backgroundColor = "0a0a0aff"
          borderColor = "262626ff"
        }
      }
    }
    componentClasses = {
      buttons = {
        borderRadius = 10
      }
      divider = {
        lightMode = {
          borderColor = "e5e5e5ff"
        }
        darkMode = {
          borderColor = "262626ff"
        }
      }
      focusState = {
        lightMode = {
          borderColor = "a1a1a1ff"
        }
        darkMode = {
          borderColor = "525252ff"
        }
      }
    }
  })
}
